---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorand-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gorand-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gorand-app
    spec:
      containers:
      - image: tecker/gorand:latest
        name: gorand
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 256Mi
            cpu: 0.2
...
---
apiVersion: v1
kind: Service
metadata:
  name: gorand-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gorand-app
  type: ClusterIP
...
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gorand-ingress
spec:
  rules:
  - host: gorand.tecker.ga
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gorand-service
            port:
              number: 80
...